"""Initial migration.

Revision ID: 021d731ad92a
Revises: 
Create Date: 2023-03-11 10:25:00.100566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021d731ad92a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_system_user', sa.Boolean(), nullable=True),
    sa.Column('is_doctor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=10000), nullable=True),
    sa.Column('department', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10000), nullable=True),
    sa.Column('img', sa.String(length=10000), nullable=True),
    sa.Column('department', sa.Integer(), nullable=False),
    sa.Column('is_top_2', sa.Boolean(), nullable=True),
    sa.Column('is_bottom_2', sa.Boolean(), nullable=True),
    sa.Column('is_top', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['department.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.Integer(), nullable=False),
    sa.Column('service', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.String(length=10000), nullable=True),
    sa.Column('appointment_time', sa.String(length=10000), nullable=True),
    sa.Column('status', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['doctor'], ['doctor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient'], ['patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('service')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('user')
    op.drop_table('department')
    # ### end Alembic commands ###
